### ISSUE TITLE
publishToMavenLocal

### ISSUE THREAD

**Issue by roxspring** [societe-generale/arch-unit-gradle-plugin#22]
The readme recommends:

> to publish in local repo during tests, use gradlew -Dmaven.repo.local=.m2/repository publishToMavenLocal

But this cannot work because the `maven-publish` plugin is not configured. Instead you get:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToMavenLocal' not found in root project 'arch-unit-gradle-plugin'.
```

**Comment by vincent-fuchs** [comment]
thanks for raising this, you're right : this is due to https://github.com/societe-generale/arch-unit-gradle-plugin/commit/d9eceb7605fe0f0101174caf00d8922b85994dcc in which I did a bit of cleanup because we don't deploy to Maven central anymore (we did initially), but to Gradle plugins repo (https://plugins.gradle.org/plugin/com.societegenerale.commons.arch-unit-gradle-plugin) .

I had forgotten that we need it to deploy locally, it should be fixed now.
